var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "            xx                                                                  ",
   "           xxxx                               oo                                ",
   "          xxxxx                                                                 ",
   "           xxx                       oo     xxx                          o      ",
   "                                           xxxxxx                               ",
   "                                              xx                                ",
   "                                   xxxxx                    xxx                 ",
   "                                    xxx                 xxxxxxxxxxx             ",
   "                       xxxxxx              o              xxxxxxx               ",
   "                     xxxxxxxxx         xxxxx                xxx                 ",
   "                      xxxxx            xxxxxxx                                  ",
   "                                                                             xx ",
   "                                               o  q                          xx ",
   "               xxxxxxx      xxxxx          xxxxxxxxx                            ",
   "                 xxxx      xxxxxxx           xxxxxx                             ",
   "                 xxx         xxxx             xxxx                              ",
   " @                                                                              ",
   "xxxxxx                                                                          ",
   " xxxxx                                                                          ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                        ss                                                        ",
   "                                                      ssssss                                                      ",
   "                                                    ssssqsssss                                                    ",
   "                                                   ssssssssssss                                                   ",
   "                                                       sss                                                        ",
   "                                                        v                                                         ",
   "                                                                                             oo                   ",
   "      @                                                                                      xx                   ",
   "  xxxxxxx                                                                                   xxxxx                 ",
   "   xxxxxx                                                                                   xxxx                  ",
   "     xxxx                                                               x    =  o            xx                   ",
   "                                                                        xxx!!!!xxx                                ",
   "                                                                      oxxxx!!!!xxxxo                              ",
   "                                                                      xxxx!!!!!!xxxxx                             ",
   "                                                     x     x         xxxx!!!!!!!!xxxxx        x     x             ",
   "                                            o       xx     xx       xxxxxx!!!!!!xxxxxxx      xx     xx            ",
   "                                  xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxx!!!!!xxxxxxx     xx",
   "                                xxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx     xx",
   "                             oxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "                            xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "                         oxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o    ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    @                          xxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx       xxx                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!xxxxxxxxxxxxxxxxx      xx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!                        x   = =                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  !!!!                                 x     o          xxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   vv                            x     xx               xxxxxxx       =                                       ",
   "                  xxx            x     xxxx              xxxxxxxxx                                            ",
   "               xxxxxxx          xx  |  xxxxx              xxxxxxxxxx =                                      o ",
   "             xxxxxxxxxx        xxx!!!!!x xxxx              xxxxxxxxxxx                                   sssss",
   "         xxxxxxxxxxxxxxxx     xxxx!!!!!x xxxxxx              xxxxxxxxxxxxx                            ssssssss",
   "                  xxxxxxxxxxxxxxxxxxxxxx xxxxxxx           xxx                                      ssssssssss",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxx         xxxx   oooo                             ssssssssssss",
   "                        xxx           xx                xxxxxx q                               sssssssssssssss",
   "                         x                             xxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxx",
   "                 xxx                           xxx   xxxxxxxxx qqqqq                           xxxx!!!!!!xxxxx",
   "                xxxxx                      xxxxxxx   xxxxxxxxxxxxxxxxxxxxx                              xxxxxx",
   "            o  xxxxx        o   =         xx          xxxxxxxxxxxxxxxxxxxxxx                                  ",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x           xxxxxxxxxxxxxxxxxxxxxxxxxxx                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   x           xxxxxxxxx                                               ",
   "!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!x   x= =        xxxxxx                                                  ",
   "!!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!xxxxxxx   x           xxxxx                                                 o ",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxx | x           xxxxx o                                            xxxx ",
   " vv       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xx          xxxxx                                 =          !!!!!!!",
   "              xxxxxxxxxxxxxxxxxxxxxxxxx!!!x           x     xxx                         xxxxxxxxxxxxxxxxxxxxxx",
   "                 xxxxxxxxxxxxxxxxxxxxxx!!!x           x              xxxxxxxx           !!!xxxxxxxxxxxxxxxxxxx",
   "                    xxxxxxxxxxxxxxxxxxxxxxxx     o o  x!!!!!!!!!!!!!!xxxxx                xxxxxxxxxxxxxxxxxxxx",
   "                     xxx     xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!xxx                  xxxxxxxxxxxxxxxxxxx ",
   "                      x      xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxxxxxx ",
   "   o                         xxxxxxxxxxxxxxx   xxxxxxx    xxxxxx                          xxxxxxxxxxxxxxxxxxx ",
   "   xxx          =              x  xxxxxxx       xxxxx     xxxx                           xxxxxxxxxxxxxxxxxxxx ",
   "   xxx                         x     xx         xxx       xxx                         xxxxxxxxxxxxxxxxxxxxxxx ",
   "   xxx                       = x           xxxxxxx        xx                            xxxxxxxxxxxxxxxxxxxxx ",
   "   xxx                         x           xxxxxxx        x                                xxxxxxxxxxxxxxxxxx ",
   "   xxxx                        xx          x                                       xxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "   xxxxx            o                       x                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxx          xxx               o o   xx                                          !!!!!!!!!!!!!!!!!!!!!xx",
   "   xxxxxxxx      xxxxx      xxxxx          x                                       !!!!xxxxxxxxxxxxxxxxxxxxxx ",
   "   x!!!!!!!!!!!!!!!v!!!!!!!!!!!x qq xxx qq x    oo   o                          = !!xxxxxxxxxxxxxxxxxxxxxxxxx ",
   "   x!!!!!!!!!!!!!!! !!!!!!!!!!!xxxxxxxxxxxxx    xx   x    x    x oo          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "   xxxxxxxxxxxxxxx   xxxxxxxxxxx           xxxx!!!!!!!x!!xxxxxxxxxxx    x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "               o                                                           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                   sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssqqqqq ",
   "                                   s q ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss       ",
   "                                     s           sssssssssssssssssssssssssssssssssssssssssssssss              ",
   "         o                           v                       v                    v                       o   ",
   "                                                                                                    sss       ",
   "                          o                                                                       sss s       ",
   "   q           q                                                      o   o                  o o osss s       ",
   "ssssssssssssssssssssss                                                                      ssssssss  s       ",
   "                                                    ssssssssssssssssssssssssssssss   ssssssssssssssssssss   ss",
   "        o                                                         ss   ss   ss  ss   ssssss                   ",
   "   q         =  s                           o                                                                 ",
   "ssssssssssssssssss                                   s=           o       o                       o    =     q",
   "        q                 o                 ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
   "ssssssssssssssssssssssssssss     sssssss     s                                                                ",
   "                         =      s            s          ss               =                                    ",
   "                                s     =      s                                                                ",
   "                                s    sssssssss                                                                ",
   "                                s                     ss                          q q                         ",
   "             o     =         ssss                                                  q                          ",
   "                              s                                                   sss                         ",
   "                          o   s                                                sssssssss      q               ",
   "                              s     o                            ss           s         s                     ",
   "             =        sssssssss    sss                  ss             s                 ss                   ",
   "                        s                                                           o    s        q           ",
   "    q                   s o            o                         ||            s    s   s                     ",
   "ssssssss                s                                                       s      s                      ",
   "sss           o sssssssss   sssssssss    s                                      s!!!!!s                       ",
   "                s       s q s      sqqqqqs                 ||                   sssssss                       ",
   "     @      sssss   o   sssss   o   ssssss                               o                  q                 ",
   "sssssssss                                 sssssssss                     sss                                   ",
   "sssssssss                   =                =s   s           q         sss    q                         q    ",
   "sssssssssssssssssssssssssssssssssssssssssssssss   s!!!!!!!!!!!!!!!!!!!!!sss!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
